- name: Create instances
  hosts: localhost
  connection: local

  vars:
    vpc_id: vpc-0f7c746d
    ami: ami-0567f647e75c7bc05
    key_pair: personal-aws
    subnet: subnet-fef8d38a

  tasks:
    - name: Create db server
      amazon.aws.ec2:
        key_name: "{{ key_pair }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          role: db
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes

    - name: Create web server
      amazon.aws.ec2:
        key_name: "{{ key_pair }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          role: web
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
